### PR TITLE
Android API level 15

### LINKED ISSUE #17: Android API Level 15 compatibility
As discussed in #14, it would be great to support Android versions down to API level 15, if possible, as mentioned by @devemux86.

According to @snodnipper, it looks like we have some uses of the static methods in java.util.Objects, which are available above API 19 (Android 4.4.+).

https://github.com/wdtinc/mapbox-vector-tile-java/blob/933fa04e2cc5629bfc1b99582da8ab170535b702/src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/TileGeomResult.java#L30

https://github.com/wdtinc/mapbox-vector-tile-java/blob/933fa04e2cc5629bfc1b99582da8ab170535b702/src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/UserDataKeyValueMapConverter.java#L39

I am not sure what else needs to be done and if these method calls can be easily converted to Android API level 15 compatibility? If it's just these [`Objects.requireNonNull`](https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#requireNonNull(T)) calls, I can create a PR adding a Util Method like:

```
requireNonNull(Object obj)
   if(obj == null)
      throw new NullPointException();
```

### PR DESCRIPTION
**Pull request by boldtrn**
This PR fixes #17.

Should I also change the two Java language level related issues mentioned in #17?

### CODE REVIEW

File: src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java [hunk 1]
```diff
@@ -71,8 +68,12 @@ public static JtsMvt loadMvt(File file,
                                  RingClassifier ringClassifier) throws IOException {
         final JtsMvt jtsMvt;
 
-        try(final InputStream is = new FileInputStream(file)) {
+        InputStream is = null;
+        try {
```
Comment (snodnipper) [inline src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java]: FYI "In addition to the Java 8 language features and APIs above, Android Studio 3.0 and later extends support for try-with-resources to all Android API levels.".

Source: https://developer.android.com/studio/write/java8-support.html

Comment (ShibaBandit) [reply src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java]: Good catch, really don't want to give up try-with-resources.

File: src/main/java/com/wdtinc/mapbox_vector_tile/util/JdkUtils.java [hunk 2]
```diff
@@ -28,4 +28,19 @@ private JdkUtils() {}
...
+
+    /**
+     * This method mimics the behavior of Objects.requireNonNull method to allow
+     * Android API level 15 backward compatibility.
+     *
+     * @param object
+     * @return object
+     * @throws NullPointerException if object is null
+     */
+    public static <T> T requireNonNull(T object) {
```
Comment (ShibaBandit) [inline src/main/java/com/wdtinc/mapbox_vector_tile/util/JdkUtils.java]: Nice.

File: src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java (hunk 1 above)
Comment (boldtrn) [reply src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java]: Thanks for finding this. Android Studio 3.0.1 complained that this would not be correct for API level 15, but probably I didn't had the "desugar" setup properly. I will revert this change then.

File: src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java [hunk 3]
```diff
@@ -596,4 +596,4 @@ private static Geometry readPolys(GeometryFactory geomFactory,
             return polygons;
         }
     }
-}
```
Comment (boldtrn) [inline src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java]: Not sure what this change is about :/. I copy pasted the MvtReader from master.

**Comment by boldtrn** [comment]
I updated this PR. Let me know if the current state works for you or if I should change anything else.

**Comment by ShibaBandit** [comment]
Pull request is looking good to me... I haven't pushed 3.0.0 yet so I'll probably update readme to list Android API 15 instead of 21.

**Comment by boldtrn** [comment]
Ah right, do you want me to update the readme, so it's in one change?

**Comment by ShibaBandit** [comment]
Sure :]

File: README.md [hunk 4]
```diff
@@ -8,7 +8,7 @@ Provides:
 
  * protoc generated model for Mapbox Vector Tiles v2.1.
  * Provides MVT encoding through use of the Java Topology Suite (JTS).
- * Android v21 compatibility (as of version 3.0.0).
+ * Android API level 15 compatibility (as of version 3.0.0).
```
Comment (boldtrn) [inline README.md]: I changed v to API level, as this seems to be  the [official name](https://source.android.com/setup/build-numbers#platform-code-names-versions-api-levels-and-ndk-releases).

File: src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java (hunk 1 above)
Comment (devemux86) [reply src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java]: >  but probably I didn't had the "desugar" setup properly

@boldtrn what do you mean?
Android Studio with default settings should work.

Comment (boldtrn) [reply src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/MvtReader.java]: Yeah I am actually not sure. Android Studio complaint about this, but only after running `Analyze->Inspect Code`. So maybe it was more of warning...

**Comment by devemux86** [comment]
Probably need updating also Changelog to mention "Android API level 15 compatibility".
